### PR TITLE
Add an Extensions type to wrap old raw-String one

### PR DESCRIPTION
**Pull request by Kerollmops**

### CODE REVIEW

**Comment by c0gent** [comment]
Looks good :)

**Comment by c0gent** [comment]
I'm going to move `Extensions` into the `platform.rs` file just to keep things tidy.

**Comment by Kerollmops** [comment]
Ok and by the way you can remove the `pub(crate)` and let the field private.
`pub(crate)` is a nightly only fetaure.

**Comment by c0gent** [comment]
`pub(crate)` is a stable feature now but I will change it to private.

**Comment by Kerollmops** [comment]
Ho ! Good to know 😄

**Pull request merged**
