### PR TITLE
Crate split

### PR DESCRIPTION
**Pull request by 01d55**
Split up the currently existing single crate into 3 with distinct purposes

The most basic is opencl_sys, nearly a simple binding and type crate but additionally with feature based conditional compilation to include or exclude functions based on which versions of the OpenCL specification they were introduced or deprecated in.

Next is opencl_core, which contains rusty but still unsafe wrappers around opencl_sys. Feature based conditional compilation is much thinner here - just enough to exclude code which depends on features introduced in 1.2.

Finally, the ocl crate still has (mostly) safe wrappers around opencl_core and opencl_sys. There's currently feature based conditional compilation that can exclude 1.2 stuff, but I consider this temporary - the desired functionality here is runtime version handling.

### CODE REVIEW

**Comment by Kerosene2000** [comment]
Do you think opencl_sys and opencl_core can be accessed by other repos and permit other people to create other ocl like crates (big wrapper) ?
That a good idea 👍

**Comment by c0gent** [comment]
Yeah that has been something I've tentatively been planning to do which is why I designed the library the way I did. I'm glad that @01d55 went ahead and got the ball rolling on this so that we can get a better idea of what it will look like split apart.

Yes, it would be a separate crate for core and sys. I'm still not 100% sure it's worth it but we'll see.

I will have some time later this week to start looking more into the details and messing around with it.

**Comment by c0gent** [comment]
I originally wanted to use this pull request as a collaboration area but I've now decided I'm going to begin by splitting up the repo right off the bat. I'll create a new branch to contain the new, hugely stripped down, `ocl` crate.

Bring any future discussion to the new tracking issue: #34.

**Comment by c0gent** [comment]
As soon as we finish the split we can focus on the versioning system.

**Pull request closed without merging**
