### PR TITLE
Merge ocl-interop 

### PR DESCRIPTION
**Pull request by Nopey**
Add ocl-interop from https://github.com/Nopey/rust-ocl-interop/
Working towards solving issue #23 
TODO: User control on what rendering API to enable interop with, enabling things such as DirectX interop, or EGL on Desktop.
TODO: Add ocl-interop to workspace root Cargo.toml

### CODE REVIEW

**Comment by c0gent** [comment]
That was fast. Looks great.

I'm headed out for the evening. I'll give it a quick double-check and merge it tomorrow or Sunday :)

**Comment by c0gent** [comment]
I know it's a nitpick but could you do a bit of clean up on the formatting to get it a bit closer to the [recommended rust style](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md)? For example spaces before and after `=` (e.g. `x=5` -> `x = 5`).

**Comment by c0gent** [comment]
Let me know your thoughts on what the interface within ocl-core and ocl should look like and we'll figure out how to wire it all up.

**Comment by Nopey** [comment]
interop needs to be told what graphics API to co-op with, GL, EGL, DX, etc.
Pass an enum to the context/propertieslist creators to tell them what API to use.
Grouping GLX & WGL into "GL" seems reasonable, since users of GL usually aren't targeting only WGL or only GLX.
Alternatively, the context/propertieslist creators could continue to receive no arguments.
Each API would have it's own creation function, probably generated with a simple macro.
The brute force detector would have to iterate through the API properties somehow.
I think theres a better way, but I havn't thought of it yet.
As for OCL and OCL-Core integration,
ocl users should only have to call a function on their ContextBuilder to enable interop, whereas
ocl-core users should probably just call upon ocl-interop directly, and deal with the returned propertieslist.

**Comment by c0gent** [comment]
That all makes sense. I leave it in your hands. Once you figure out how you want it and start coding it up I'll throw in my two cents. Until then, feel free to bounce ideas off of me if needed :)

**Pull request merged**
