### PR TITLE
Implement compile_program && link_program in ocl-core

### PR DESCRIPTION
**Pull request by romankoblov**
Hello! There is implementation for compile/link_program in ocl-core.
It allows to add headers for kernel separately with specifying names, 
so compilation errors will be more clear (down to specific file), like this:
```
    world.cl:3:31: error: use of undeclared identifier 't'
            printf("world\n", t);
```
This functions works correctly on Linux (Intel, NVIDIA), but fails on MacOS
OpenCL implementation (Intel, AMD).

### CODE REVIEW

**Comment by dmarcuse** [comment]
Seems to fail with `CL_LINK_PROGRAM_FAILURE` on Linux with AMD. I'll see if I can find anything in the OpenCL program build log.

**Comment by romankoblov** [comment]
Sorry, was my mistake during tests cleaning, should work on Linux now.

**Comment by c0gent** [comment]
Looks great! I may reword the documentation a bit but really nice work.

**Comment by c0gent** [comment]
Merged as a6693a72eba048624d866ce190831141c0f7f411. Thanks!

**Comment by dmarcuse** [comment]
Would it be possible to extend this with another PR adding a way to link against existing `Program`s while using `ProgramBuillder`?

**Comment by romankoblov** [comment]
I'm not sure how properly fit that in ProgramBuillder, maybe you will tell more about your use case?
Problem that ProgramBuilder::build() returns "builded" program (ProgramBinaryType::EXECUTABLE), but link_program requires "compiled" program (COMPILED_OBJECT), at least it fails for me on linking already build programs (link_program returns null_ptr).
As for my use-case I do API like that, which I can port to ProgramBuilder if it will be enough for you and @c0gent will agree:
```rust
builder.add_header(header_src, header_name);
builder.set_source(src);
builder.build();
```
or it can be like this:
```rust
let program_builder1 = ProgramBuilder::with_source(...); // no build here
let program_builder2 = ProgramBuilder::with_source(...);
/// Returns Program
let p = ProgramBuilder::with_source(...).compile(&[&program_builder1, &program_builder2]); 
```

**Pull request closed without merging**
