### PR TITLE
Build script for OpenCL.lib

### PR DESCRIPTION
**Pull request by pravic**
In respect of #28 :)

### CODE REVIEW

**Comment by c0gent** [comment]
Nice :)

Would it be better to put this in [cl-sys](https://github.com/cogciprocate/cl-sys)?

**Comment by pravic** [comment]
Really.

**Comment by c0gent** [comment]
Ummm. I dunno. I'm happy to put it there myself if that's what you're implying. :)

Don't you think thats the best place for it?

I didn't mean to ask you to do even more work. :)

**Comment by pravic** [comment]
Here we go: cogciprocate/cl-sys#2.

**Pull request closed without merging**
