### PR TITLE
add build_unfinished() method

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by TyOverby** [comment]
This skips the "all parameters are set" check in KernelBuilder.

(This implementation has not yet been tested, I just thought I'd get it out there early for review)

**Comment by c0gent** [comment]
Yes I'll need to think about this just a bit. One of the design intentions with `Kernel` is to ensure that nothing unsafe could accidentally happen when setting/accessing buffers later. I'm going to need to make sure that I didn't make any assumptions that might be violated by this change but I can't think of any reason they would be.

Thanks again for your input and your help!

**Comment by TyOverby** [comment]
Yeah, I'm not too happy with this solution either. Even with `build_unfinished`, I have to do this unfortunate copy-pate of registering the type with the builder, and then re-specifying it with the Kernel.

[Example here](https://github.com/TyOverby/implicit-gpu/commit/d5f15abaaa8ed8b090a1b7a7436af8c82eb475c3#diff-098d82c2ec70053dd9f4dbc88a2bb199R24)

I really don't like this because for my default values for scalars, if I register them with the builder and then forget to write the Kernel-modifying code, I get that default value without any warnings.

**Comment by c0gent** [comment]
Closing for now. See #121.

**Pull request closed without merging**
