### PR TITLE
Add a second image example.

### PR DESCRIPTION
**Pull request by drahnr**
Note that the `ocl` version is fixed to `0.10.0`, I would appreciate if someone could take a look at why it does not work with `ocl 0.11.0`.

There is a `test.jpg` included which is taken from [fedora magazine](https://fedoramagazine.org/introducing-extra-wallpapers-fedora-24/) released under CC-BY-SA which is also stated in the example `README.md`.

The example itself is a semi-scaleable kernel version of RGBA->GRAY.

This is related to #35 since it shows the resulting, saved images are not saved without calling `finish()` after the cl buffer `read()` is enqueued.

### CODE REVIEW

**Comment by c0gent** [comment]
Looks great. Very nice work.

This is the most valuable kind of feedback as I'm unable to reproduce the original problem on any of my hardware. It appears as though on your platform, calling `Image::read().enq()` (aka: `core::enqueue_read_image` -> `ffi::clEnqueueReadImage`) is not properly allowing the call to complete before returning. This _should_ be a blocking call that waits until the buffer data has been read to host memory. It's apparently not working as intended on your platform and is yet another instance of sloppy driver design (Apple/NVIDIA by chance?).

The 'redundant' calls to `.finish()` are extremely cheap so if you ever run into other occurrence of this in any examples or tests please throw them in and create another pull request even if you're not sure it's necessary.

As to the `0.10.0`/`0.11.0` issue with your new example, I'm unfortunately unable to reproduce that either. I'll change the `image` dependency to use the newest version available but this should only get rid of some old warnings from 0.7.0. I'm not sure what the problem is there. I'm going to merge this pull request + the latest version updates for both the `image` and `ocl` crates. Please go ahead and do a fresh pull from `master` then try to run your new example. File a new issue if the problem still exists so we can tackle that one.

On a final note, I assume we need to add a `.finish()` to the original `images` example. As I cannot reproduce the original problem please also add that call and verify that it is working as intended (We may as well leave the original example intact but if you want to rename it or get rid of it altogether please do so -- I'll leave it in your hands).

Again thanks for all of your help. Get back to me on those last two outstanding items at your leisure :)

**Comment by c0gent** [comment]
@drahnr:

I am getting intermittent segfaults running this on ocl `0.11.0` on Intel drivers (Linux). AMD/Windows, AMD/Linux, NVIDIA/Linux, and NVIDIA/Windows do not appear to reproduce this which indicates that there is indeed a bug somewhere (running OpenCL on the CPU often reveals kernel bugs that the GPU doesn't due to the fact that system memory is used). It's possible there is a bug somewhere in one of the the image processing API calls but a kernel bug seems more likely.

I'll get to the bottom of it as soon as I can.

**Comment by drahnr** [comment]
Ok, interesting.

I ran it on my Fedora 24 AMD64 laptop with an Intel IGP.

```
Number of platforms                               2
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 1.2 beignet 1.1.1 (git-9043d32)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_khr_icd
  Platform Extensions function suffix             Intel
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 

  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 12.0.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  Device Name                                     Intel(R) HD Graphics 5500 BroadWell U-Processor GT2
  Device Vendor                                   Intel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 beignet 1.1.1 (git-9043d32)
  Driver Version                                  1.1.1
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.1.1 (git-9043d32)
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               23
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  Preferred work group size multiple              16
  Preferred / native vector sizes                 
    char                                                16 / 8       
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1073741824 (1024MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8192
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               65536 (64KiB)
  Max constant buffer size                        134217728 (128MiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      80ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 <printDeviceInfo:138: get   SPIR versions size : error -30>
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                __cl_copy_region_align4;__cl_copy_region_align16;__cl_cpy_region_unalign_same_offset;__cl_copy_region_unalign_dst_offset;__cl_copy_region_unalign_src_offset;__cl_copy_buffer_rect;__cl_copy_image_1d_to_1d;__cl_copy_image_2d_to_2d;__cl_copy_image_3d_to_2d;__cl_copy_image_2d_to_3d;__cl_copy_image_3d_to_3d;__cl_copy_image_2d_to_buffer;__cl_copy_image_3d_to_buffer;__cl_copy_buffer_to_image_2d;__cl_copy_buffer_to_image_3d;__cl_fill_region_unalign;__cl_fill_region_align2;__cl_fill_region_align4;__cl_fill_region_align8_2;__cl_fill_region_align8_4;__cl_fill_region_align8_8;__cl_fill_region_align8_16;__cl_fill_region_align128;__cl_fill_image_1d;__cl_fill_image_1d_array;__cl_fill_image_2d;__cl_fill_image_2d_array;__cl_fill_image_3d;
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_spir cl_khr_icd

  Platform Name                                   Clover
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [Intel]
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clCreateContext(NULL, ...) [default]            Success [Intel]
  clCreateContext(NULL, ...) [other]              <error: no devices in non-default plaforms>
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics 5500 BroadWell U-Processor GT2
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics 5500 BroadWell U-Processor GT2

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.
```

**Comment by drahnr** [comment]
Regarding the dependency problem I created #37

**Comment by drahnr** [comment]
I'll double the check the blue square image example.

**Comment by c0gent** [comment]
Was just glancing at your kernel code and I'm pretty sure I've identified the problem. I'll put up a pull request you can have a look at as soon as I get a chance.

**Comment by c0gent** [comment]
Have a look at https://github.com/cogciprocate/ocl/pull/38 and let me know what you think...

Changes: 

- [minor] Use the `find_folder` crate and `Program::builder().src_file(...)` to load the kernel file more robustly and eliminate the need for the `read_kernel` function.
- Fix the segfault inducing overflow in the global work size calculation and create two separate kernels "patches" and "unrolled". Notes listed at the top of `main.rs` describing why.

The original workgroup size calculation was incorrect, and was accessing memory beyond the bounds of the image buffer, causing segfaults (when the CPU was being used). GPUs usually don't care if you read or write to invalid memory but in your case and are extremely forgiving of overruns but because you're using the integrated graphics (which counts as a GPU as far as OpenCL is concerned), and therefore system memory, your system segfaulted when mine didn't at first (even when I ran it on my CPU for the first few times just due to the randomness of how the memory was allocated). If you had run this on an external GPU device this bug may have gone unnoticed by any of us for who knows how long.

**Comment by c0gent** [comment]
I just made some additions and corrections.

**Comment by c0gent** [comment]
Posted in the wrong place :/

**Pull request merged**
