### PR TITLE
Fixed opencl compilation error while trying to pass options

### PR DESCRIPTION
**Pull request by Kerosene2000**

### CODE REVIEW

**Comment by c0gent** [comment]
Looks good. For whatever reason my hardware has always been accepting compilation flags without the space.

Out of curiousity, which OS/hardware are you on (if I've asked you this before I can't remember).

**Comment by Kerosene2000** [comment]
I was on an iMac late 2012 on OS X el capitan

**Comment by Kerosene2000** [comment]
I don't understand why on my mac it doesn't compile, openCL doesn't like two or more spaces before first  compilation options... strange and ugly !

**Comment by c0gent** [comment]
Everything is always a hassle on a mac. It's been that way for, what, 20 years now.

**Comment by Kerosene2000** [comment]
Haha you're right ! 😄

**Pull request merged**
