### PR TITLE
Clippy-ing a little

### PR DESCRIPTION
**Pull request by Kerosene2000**
Using [rust-clippy](https://github.com/Manishearth/rust-clippy) to clean a little 👍

### CODE REVIEW

**Comment by c0gent** [comment]
Ok I'm working on a test so I can get these merged. Thanks for making this one separate.

**Comment by c0gent** [comment]
I made changes to master so you might have to run this again.

**Comment by Kerosene2000** [comment]
For the moment I am fighting with `multirust`/`rust`/`cargo`, trying to compile `rust-clippy` in nightly 😢 
I get this f*cking error, and don't know why (stable works fine but I need nightly)
```bash
error: failed to lock file: /nfs/2013/c/crenault/Documents/rust-clippy/Cargo.lock

Caused by:
  Operation not supported (os error 45)
```

**Comment by c0gent** [comment]
Well to solve that you could try rebooting maybe... perhaps the file didn't get closed properly....

but...

hang on... let me commit some new changes before you clippy....

Please re-pull from master in a moment...

**Comment by c0gent** [comment]
Ok go ahead now. I won't do any more changes until you're done.

**Comment by Kerosene2000** [comment]
It seems that's not a system problem but a `rust`/`cargo`/`clippy` problem, because even after a reboot, I got the same error...
Strange, on my personal computer it works fine...
I will do this in the evening (GMT+2) with my own computer 🍓

**Comment by c0gent** [comment]
Sounds good.

**Comment by Kerosene2000** [comment]
what do you think about that [enum_clike_unportable_variant](https://github.com/Manishearth/rust-clippy/wiki#enum_clike_unportable_variant) ?

```
src/core/mod.rs:838:15: 68:71
warning: Clike enum variant discriminant is not portable to 32-bit targets,
#[warn(enum_clike_unportable_variant)] on by default
```

**Comment by c0gent** [comment]
Yeah can't have any of those but there shouldn't be one at `core/mod.rs::838` that's weird.

**Comment by c0gent** [comment]
Oh wait.... I misread that... yeah it's complaining about repr(C)... 

Ignore that.

**Comment by c0gent** [comment]
@Kerosene2000:
I really hate the indentation changes on everything but I didn't notice until after I committed. Which tool modified the indentation? I should have looked more carefully.

Is there any way you can revert the just the indentation to how it was before so that I don't have to try to revert the commit(s)?

**Comment by c0gent** [comment]
There must be some way to set it NOT to align indentation with brackets. I hate that style.

**Comment by c0gent** [comment]
I went ahead and rolled back to the commit right before I applied that pull request.

I'm fine if you want to do another pass of clippy but *please* do not use rustfmt at all.

Thanks.

**Comment by Kerosene2000** [comment]
That's why I do **2** different pull requests, one that just [`clippy`](https://github.com/cogciprocate/ocl/pull/22) the code and another that [`rustfmt`](https://github.com/cogciprocate/ocl/pull/24)...

I will do a new pull request with only `clippy` things...

**Comment by c0gent** [comment]
You did nothing wrong. I appreciate you separating thing out into different requests. Your work has been good. It's my fault for not looking closely at the changes and discussing them with you first. :)

**Comment by Kerosene2000** [comment]
Haha no problem guy ! 😺

**Pull request merged**
